[workspace]
members = [
    "cli",
    "energy-monitor", "modbus-proxy",
    "quantities",
]
resolver = "3"

[workspace.lints.clippy]
future_not_send = "allow"
type_repetition_in_bounds = "allow"

[workspace.lints.clippy.pedantic]
level = "warn"
priority = -1

[workspace.lints.clippy.nursery]
level = "warn"
priority = -1

[workspace.lints.clippy.all]
level = "warn"
priority = -1

[profile.release]
codegen-units = 1
debug = "full"
lto = "thin"
