[workspace]
resolver = "3"
members = ["cli"]

[workspace.lints.clippy]
type_repetition_in_bounds = "allow"

[workspace.lints.clippy.pedantic]
level = "warn"
priority = -1

[workspace.lints.clippy.nursery]
level = "warn"
priority = -1

[workspace.lints.clippy.all]
level = "warn"
priority = -1

[profile.release]
codegen-units = 1
debug = "full"
lto = "thin"
