[package]
name = "fennec-cli"
description = "FoxESS home battery steering based on Next Energy or Frank Energie real-time prices"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[badges]
is-it-maintained-issue-resolution = { repository = "eigenein/fennec" }
is-it-maintained-open-issues = { repository = "eigenein/fennec" }

[dependencies]
anyhow = "=1.0.100"
average = "=0.16.0"
bon = "=3.8.1"
chrono = { version = "=0.4.43", default-features = false, features = ["clock", "serde"] }
comfy-table = "=7.2.2"
derive_more = { version = "=2.1.1", features = ["full"] }
dotenvy = "=0.15.7"
http = "=1.4.0"
enumset = "=1.1.10"
humantime = "=2.3.0"
itertools = "=0.14.0"
md5 = "=0.8.0"
serde_json = "=1.0.149"
serde_qs = "=1.0.0-rc.5"
toml = "=0.9.10"
tracing = "=0.1.44"
tracing-subscriber = "=0.3.22"

[dependencies.serde]
version = "=1.0.228"
features = ["derive"]

[dependencies.serde_with]
version = "=3.16.1"
features = ["chrono"]

[dependencies.clap]
version = "=4.5.54"
features = ["cargo", "derive", "env", "unicode"]

[dependencies.ureq]
version = "=3.1.4"
features = ["json", "brotli", "gzip"]

[dev-dependencies]
approx = "=0.5.1"
ordered-float = "=5.1.0"
