name: ğŸ§ª Check

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - "README.md"
      - ".dockerignore"
      - ".gitignore"
      - "renovate.json"
      - "rustfmt.toml"
      - ".goreleaser.yaml"
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: "always"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  check:
    name: ğŸ§ª Check
    runs-on: ubuntu-latest

    steps:
      - name: â¬†ï¸ Update Rust
        run: rustup update --no-self-update

      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v5

      - name: âš¡ï¸ Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: âš¡ï¸ Shared Compilation Cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: ğŸ§ª Install coverage tools
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: ğŸ§ª Test
        run: cargo llvm-cov --codecov --output-path=codecov.json --workspace -- --include-ignored
        env:
          TZ: Europe/Amsterdam

      - name: ğŸ“¤ Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: eigenein/fennec
          files: codecov.json

      - name: ğŸ’¬ Clippy
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --workspace
          reporter: github-check
        continue-on-error: true
